config/routes.rb
Rails.application.routes.draw do
  root 'navigation#index'
  devise_for :users
  resources :item_names

  get '/my_items' => 'item_names#personal_index'
  get '/all_items' => 'item_names#index'

end

app/models/item_name.rb
class ItemName < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_names_controller.rb
class ItemNamesController < ApplicationController
  before_action :set_item_name, only: [:show, :edit, :update, :destroy]

  # GET /item_names
  # GET /item_names.json
  def index
    @item_names = ItemName.all
  end

  def personal_index
    @item_names = ItemName.where(user: current_user)
  end

  # GET /item_names/1
  # GET /item_names/1.json
  def show
  end

  # GET /item_names/new
  def new
    @item_name = ItemName.new
  end

  # GET /item_names/1/edit
  def edit
  end

  # POST /item_names
  # POST /item_names.json
  def create
    @item_name = ItemName.new(item_name_params)

    respond_to do |format|
      if @item_name.save
        format.html { redirect_to @item_name, notice: 'Item name was successfully created.' }
        format.json { render :show, status: :created, location: @item_name }
      else
        format.html { render :new }
        format.json { render json: @item_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_names/1
  # PATCH/PUT /item_names/1.json
  def update
    respond_to do |format|
      if @item_name.update(item_name_params)
        format.html { redirect_to @item_name, notice: 'Item name was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_name }
      else
        format.html { render :edit }
        format.json { render json: @item_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_names/1
  # DELETE /item_names/1.json
  def destroy
    @item_name.destroy
    respond_to do |format|
      format.html { redirect_to item_names_url, notice: 'Item name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_name
      @item_name = ItemName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_name_params
      params.require(:item_name).permit(:name, :user_id)
    end
end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController
  def index
    if !current_user.nil?
      @user = current_user
      render '../views/user/pantry.html.erb'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_names_helper.rb
module ItemNamesHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/views/item_names/_form.html.erb
<%= form_for(@item_name) do |f| %>
  <% if @item_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_name.errors.count, "error") %> prohibited this item_name from being saved:</h2>

      <ul>
      <% @item_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_names/edit.html.erb
<h1>Editing Item Name</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_name %> |
<%= link_to 'Back', item_names_path %>

app/views/item_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Names</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_names.each do |item_name| %>
      <tr>
        <td><%= item_name.name %></td>
        <td><%= item_name.user %></td>
        <td><%= link_to 'Show', item_name %></td>
        <td><%= link_to 'Edit', edit_item_name_path(item_name) %></td>
        <td><%= link_to 'Destroy', item_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item name', new_item_name_path %>

app/views/item_names/new.html.erb
<h1>New Item Name</h1>

<%= render 'form' %>

<%= link_to 'Back', item_names_path %>

app/views/item_names/personal_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Names</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
    </tr>
  </thead>

  <tbody>
    <% @item_names.each do |item_name| %>
      <tr>
        <td><%= link_to item_name.name, item_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_name_path %>

app/views/item_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item_name.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @item_name.user %>
</p>

<%= link_to 'Edit Name', edit_item_name_path(@item_name) %> |         <td><%= link_to 'Delete', @item_name, method: :delete, data: { confirm: 'Are you sure?' } %></td> | <%= link_to 'Back', item_names_path %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header"><a class="navbar-brand" href="/"><span class="green">Pantry Planner</span></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-menubuilder">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if user_signed_in? %>
            <li>
              <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
            </li>
          <% else %>
            <li>
              <%= link_to('Sign In', new_user_session_path)  %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PantryPlanner</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
  </head>
  <body>
    <%=render 'layouts/navbar'%>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/navigation/index.html.erb
<h1>Welcome to Pantry Planner</h1>

<%= link_to "Sign Up", new_user_registration_path %><br />

app/views/user/_header_message.html.erb
<h1>Your Pantry</h1>

app/views/user/pantry.html.erb
<%= render 'user/header_message' %>
<%= @user.email %>
<%= link_to 'New Item', new_item_name_path %>